config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/tasks", to: "tasks#index"
  get "/tasks/new", to: "tasks#new"
  post "/tasks", to: "tasks#create"
  get "/tasks/:id", to: "tasks#show", as: 'task'
  get "/tasks/:id/edit", to: "tasks#edit", as: 'edit_task'
  patch "/tasks/:id", to: "tasks#update"
  delete "/tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :complete]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end
  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  def completed
   @task.completed = true
   @task.save
   redirect_to task_path(@task)
  end



  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
  <div class="fiel">
  <%= f.label :title %><br>
  <%= f.text_field :title %>
  </div>
  <div class="field">
  <%= f.label :details %><br>
  <%= f.text_field :details %>
  <div class="field">
    <%= f.check_box :completed %>
    <%= f.label :completed %>
  </div>
  </div>
  <div class="action">
  <%= f.submit %>
  </div>
<% end %>

app/views/tasks/destroy.html.erb
<h1>Destroy <%= @task.title %></h1>

<%= render 'form' %>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <br>
      <h1>Edit <%= @task.title %></h1>

      <%= render 'form' %>
    <hr>
      <%= link_to "go back to task list", tasks_path %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <br>
      <h1>All your tasks</h1>
      <ul>
        <% @tasks.each do |task| %>
          <li><%= task.completed ? "☑︎" : "☐" %>
            <%= link_to task.title, task_path(task.id) %></li>
        <% end %>
        <hr>
        <%= link_to "Create a task", tasks_new_path %>
      </ul>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <br>
      <h1>Add a new task <%= @task.title %></h1>

      <%= render 'form' %>
    <hr>
      <%= link_to "go back to task list", tasks_path %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <br>
      <h3>Task details</h3>
      <ul>
        <li>
          <%= @task.details %>
        </li>
      </ul>
      <hr>
      <%= link_to "Update a task", edit_task_path(@task) %>
      <%= link_to "Destroy a task", task_path(@task), method: "delete", data: {confirm: "Are you sure"} %>
      <hr>
      <%= link_to "go back to task list", tasks_path %>
    </div>
  </div>
</div>